// Lista completa de especialidades médicas en orden alfabético
export const MEDICAL_SPECIALTIES = [
  "Alergología e Inmunología Clínica",
  "Anestesiología y Reanimación",
  "Anatomía Patológica",
  "Angiología y Cirugía Vascular",
  "Bioquímica Clínica",
  "Cardiología",
  "Cirugía Cardiovascular",
  "Cirugía General y del Aparato Digestivo",
  "Cirugía Maxilofacial",
  "Cirugía Ortopédica y Traumatología",
  "Cirugía Pediátrica",
  "Cirugía Plástica, Estética y Reparadora",
  "Cirugía Torácica",
  "Dermatología Médico-Quirúrgica y Venereología",
  "Endocrinología y Nutrición",
  "Farmacología Clínica",
  "Gastroenterología",
  "Genética Médica",
  "Geriatría",
  "Ginecología y Obstetricia",
  "Hematología y Hemoterapia",
  "Hepatología",
  "Infectología",
  "Medicina de Emergencias",
  "Medicina del Deporte",
  "Medicina del Trabajo",
  "Medicina Familiar y Comunitaria",
  "Medicina Física y Rehabilitación",
  "Medicina General",
  "Medicina Intensiva",
  "Medicina Interna",
  "Medicina Legal y Forense",
  "Medicina Nuclear",
  "Medicina Preventiva y Salud Pública",
  "Microbiología y Parasitología",
  "Nefrología",
  "Neonatología",
  "Neumología",
  "Neurocirugía",
  "Neurofisiología Clínica",
  "Neurología",
  "Oftalmología",
  "Oncología Médica",
  "Oncología Radioterápica",
  "Otorrinolaringología",
  "Pediatría y sus Áreas Específicas",
  "Psiquiatría",
  "Radiodiagnóstico",
  "Reumatología",
  "Urología"
] as const;

export type MedicalSpecialty = typeof MEDICAL_SPECIALTIES[number];