// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkmmqwcjwebszfugkmlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrbW1xd2Nqd2Vic3pmdWdrbWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1Mzk5MjcsImV4cCI6MjA3MTExNTkyN30.w3TBzxq5OVFBkRx9rhdaTlbhY1_-zDCsLfulgNYe-Hk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});